spring:
  application:
  name: user-service

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/users
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

aws:
  s3:
    endpoint: http://localhost:9000
    access-key: minio
    secret-key: changeme
    bucket-name: user_documents